name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["*"]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v3

      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup target add wasm32-unknown-unknown

      - name: Build contract
        run: cargo build

      - name: Run tests
        run: cargo test
